CREATE DATABASE IF NOT EXISTS STORE;

USE STORE;

CREATE TABLE COMPANY (
	ID_COMPANY VARCHAR(255) NOT NULL,
    NAME_COMPANY CHAR(255) NOT NULL,
    CELL_COMPANY VARCHAR(15), 
    EMAIL_COMPANY VARCHAR(80) NOT NULL,
    PRIMARY KEY (ID_COMPANY)
);

CREATE TABLE PRODUCTS (
	ID_PRODUCT VARCHAR(255) NOT NULL,
    COMPANY_ID_COMPANY VARCHAR(255) NOT NULL,
    NAME_PRODUCT VARCHAR(80) NOT NULL,
    DESC_PRODUCT VARCHAR(255),
    VALUE_PRODUCT NUMERIC(9,2) NOT NULL,
    PRIMARY KEY (ID_PRODUCT),
    FOREIGN KEY (COMPANY_ID_COMPANY) REFERENCES COMPANY(ID_COMPANY)
);

INSERT INTO COMPANY (ID_COMPANY, NAME_COMPANY, CELL_COMPANY, EMAIL_COMPANY) VALUES 
	("s5pp2zrdt6nmeqzzb1fh4m", "COMPANY_1", null, "company@test.com");
    
INSERT INTO PRODUCTS (ID_PRODUCT, COMPANY_ID_COMPANY, NAME_PRODUCT, DESC_PRODUCT, VALUE_PRODUCT) VALUES
	("2milkqunx58gxi3q6xfqat","s5pp2zrdt6nmeqzzb1fh4m", "PRODUCT 1", null, 69.24);